# Generated by Django 4.2.14 on 2024-07-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
