# Generated by Django 4.2.14 on 2024-07-18 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_author_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default='nice', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in the format"+829399484"', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
